[general]
environment = "PRODUCTION"

[storage]
postgres_dsn = "postgres://username:password@host:5432/database"
redis_dsn = "redis://username:password@host:6379/database"

[security]
itsdangerous_secret = "SECRET_KEY"
