[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name        = "uploader-backend"
version     = "0.0.1"
description = "The backend API for my cdn uploader."
authors     = ["Axel <axelancerr@gmail.com>"]


[tool.poetry.dependencies]
python            = "^3.10.0"
aiohttp           = "~3.8.0"
asyncpg           = "~0.26.0"
colorama          = "~0.4.0"
dacite            = "~1.6.0"
toml              = "~0.10.0"
typing_extensions = "~4.4.0"


[tool.pyright]
include                = ["launcher.py", "uploader"]
pythonVersion          = "3.10"
typeCheckingMode       = "strict"
useLibraryCodeForTypes = true

reportUnknownMemberType  = false
reportMissingTypeStubs   = false
reportPrivateImportUsage = false
